src/aind_data_transfer_service/server.py

Closes #109 
- Sorts jobs with most recent at top

fix: update jobs sort order

---

pyproject.toml
tests/test_server.py

Closes #117 
- Updates aind-data-transfer-models to v0.5.1. This will allow users to add custom slurm settings to their upload jobs.

fix: updates models to allow user to input slurm settings

---

src/aind_data_transfer_service/models.py
src/aind_data_transfer_service/server.py
src/aind_data_transfer_service/templates/job_status.html
src/aind_data_transfer_service/templates/job_status_table.html
tests/resources/airflow_dag_run_response.json
tests/test_server.py

closes #128
- Add collapsable Filters UI to filter jobs by  **status**, **submit date range**
- or, search by **job id** (exact match only)
- Update `/api/v1/get_job_status_list`:
- Query filters for `state`, `execution_date_lte`, `execution_date_gte` (must be within 14 days), and `dag_run_id`
- Uses Airflow ListDagRuns and GetDagRun
---
**Default**:
---
**Filter job status:**
---
**Filter by submit date range:**
---
**Search by job id:**
---
**Job id not found:**
---

feat: add filters in jobs status page

---

src/aind_data_transfer_service/templates/job_status.html
src/aind_data_transfer_service/templates/job_status_table.html
src/aind_data_transfer_service/templates/job_tasks_table.html
src/aind_data_transfer_service/templates/task_logs.html

- Makes headers and tables smaller for display on small laptop screens
- Removes extra "Close" button on popups
- Displays job id and data asset name in one line in Logs popup
---
**Before (ThinkPad screen)**
---
**Now**
---

feat: smaller views for laptop screens

---

pyproject.toml
src/aind_data_transfer_service/configs/job_configs.py
src/aind_data_transfer_service/configs/job_upload_template.py
src/aind_data_transfer_service/server.py
tests/test_configs.py
tests/test_hpc_models.py
tests/test_server.py

Closes #141 
- Upgrades aind-data-transfer-service-models to v0.6.2
- Removes aind-data-schema from dependencies
- Adds unit test to verify users can set aind-metadata-mapper settings

feat: upgrades models to v0.6.2

---

docs/source/UserGuide.rst

- Adds examples for requesting creation of session.json file
- Adds example on how to request a SmartSPIM job

Docs schema v1.0

---

pyproject.toml
tests/test_server.py

Closes #158
- Updates aind-data-transfer-models version, which has a validation wrapper to allow for computed_fields such as s3_prefix to present in the json object being de-serialized.

fix: round_trip validation issues

---

docs/source/Contributing.rst
pyproject.toml
src/aind_data_transfer_service/log_handler.py
src/aind_data_transfer_service/server.py
tests/test_log_handler.py
tests/test_server.py

Closes #188 
- Adds a handler to log messages to Loki Server
- Logs stack trace when an exception happens

feat: adds log handler

---

src/aind_data_transfer_service/models.py
src/aind_data_transfer_service/server.py
src/aind_data_transfer_service/templates/job_status.html
tests/test_server.py

closes #180
This PR enables users to search all jobs by asset name or job id.
- GET `/api/v1/get_job_status_list?get_all_jobs=true`:  get all jobs from airflow that match default or provided status and submit time range
- Uses httpx aysnc client to send requests concurrently to airflow. Takes ~3s to fetch ~1000 jobs.
- Add "Advanced Search" options in job status page
- Default table is still original table that gets 1 page of jobs at a time
- If the user enables the advanced search toggle, the full jobs table is shown instead.
- Full jobs table uses JS [Datatables library](https://datatables.net/) to render and search full jobs list, fully in client-side.
- Full jobs table has same UI rendering (status colors, task buttons, etc), pagination, etc.
- User can search by asset name or job id …

feat: search all jobs by asset name or job id

---

src/aind_data_transfer_service/templates/job_status.html

- Adds tasks modal in the full jobs table to match the one in the default table.

feat: tasks modal in full jobs table

---

docs/source/UserGuide.rst
src/aind_data_transfer_service/models.py
src/aind_data_transfer_service/server.py
tests/test_server.py

closes #195 (rescoped from #107)
This PR introduces a new endpoint to validate raw json against aind-data-transfer-models.
- POST `/api/v1/validate_json`
- Example added in User Guide

feat: endpoint to validate json

---

docs/source/UserGuide.rst
pyproject.toml
tests/test_csv_handler.py

Closes #196
- Updates minor version of aind-data-transfer-models
- Updates docs and tests to accommodate for deprecated field

feat: update data transfer models

---

docs/source/Contributing.rst
docs/source/UserGuide.rst
pyproject.toml
src/aind_data_transfer_service/models.py
src/aind_data_transfer_service/server.py
src/aind_data_transfer_service/templates/index.html
src/aind_data_transfer_service/templates/job_params.html
src/aind_data_transfer_service/templates/job_status.html
tests/resources/describe_parameters_response.json
tests/resources/get_parameter_response.json
tests/test_server.py

closes #202 
This PR adds apis to list and download parameters from AWS param store, and a new Job Parameters page to display parameters:
AWS parameters are expected to be at `/aind/{env}/airflow/variables/job_types/{job_type}/tasks/{task_id}`
**Api:**
- [GET] `/api/v1/parameters`: uses boto3 describe_parameters to list params
```json
{
"message": "Retrieved job parameters",
"data": [
{
"name": "/aind/dev/airflow/variables/job_types/ecephys/tasks/expand_pipelines",
"last_modified": "2025-01-23T11:50:04.535000-08:00",
"job_type": "ecephys",
"task_id": "expand_pipelines"
},
{
"name": "/aind/dev/airflow/variables/job_types/ecephys_opto/tasks/expand_pipelines",
"last_modified": "2025-01-23T11:50:04.605000-08:00",
"job_type": "ecephys_opto",
"task_id": "expand_pipelines"
},
...
```
- [GET] …

feat: job types parameters

---

src/aind_data_transfer_service/models.py
src/aind_data_transfer_service/models/core.py
src/aind_data_transfer_service/server.py
src/aind_data_transfer_service/templates/job_params.html
tests/resources/describe_parameters_response.json
tests/test_core.py
tests/test_server.py

closes #217
This PR adds v2 endpoints to vaidate and submit jobs, as well as 
- POST `/api/v2/validate_json`
- POST `/api/v2/submit_jobs`
- GET `/api/v2/parameters`
- GET `/api/v2/parameters/job_types/{job_type:str}/tasks/{task_id:str}`
Additionally, the Job Parameters page was updated so that users can toggle between viewing v1 and v2. The default job_type is shown on default.

feat: v2 endpoints

---

src/aind_data_transfer_service/models/internal.py
src/aind_data_transfer_service/server.py
src/aind_data_transfer_service/templates/job_params.html
tests/resources/describe_parameters_response.json
tests/test_server.py

Display expanded task params from `job_types/v2/{job_type}/tasks/{task_id}/{modality_abbreviation}`

feat: v2 params with optional modality

---

src/aind_data_transfer_service/models/core.py
src/aind_data_transfer_service/server.py
tests/test_core.py
tests/test_server.py

closes #60 
This PR adds validation to prevent users from submitting duplicate jobs:
- Adds validator to check that `SubmitJobRequestV2.upload_jobs` are distinct.
- If the s3_prefixes are the same, full job configs are compared since chunked jobs may have the same prefix.
- Jobs submitted to `/api/v2/submit_jobs` or `/api/v2/validate_json` additionally check against currently running or queued jobs.

feat: prevent duplicate upload jobs

---

pyproject.toml

closes #269 
Pins mapper to latest version (v0.27.2). Let me know if it's safe to do a lower bound pin instead

build: upgrades mapper pin

---

docs/source/Contributing.rst
docs/source/UserGuideV1.rst
docs/source/UserGuideV2.rst
src/aind_data_transfer_service/models/internal.py
src/aind_data_transfer_service/server.py
src/aind_data_transfer_service/templates/admin.html
src/aind_data_transfer_service/templates/job_params.html
tests/resources/describe_parameters_response.json
tests/resources/put_parameter_response.json
tests/test_server.py

closes #261
This PR includes the following:
- New endpoint to submit a parameter value to AWS. Checks that user is signed in.
- UI modals to edit existing parameter or add a new parameter (only visible for authenticated users).
- Basic validation is done both client- and server-side (JSON serialization, no spaces or slashes in param names).
- Reset: reload from AWS
- Submit: validate json and submit updated parameter value to AWS
- Dropdowns: select Job Type (also can provide new value), Task Id (also can provide new value), and Modality (only for modality and CO tasks)
- Reset: clear dropdowns and json textarea
- Submit: validate dropdowns and json and submit updated parameter value to AWS

feat: admins can add/edit job type parameters in UI

---

src/aind_data_transfer_service/hpc/client.py
src/aind_data_transfer_service/server.py
tests/test_hpc_client.py
tests/test_server.py

closes #105, fixes #270
Replaces all synchronous get/post `requests` with `httpx.AsyncClient`. This will make all of the following non-blocking: hpc client, submit jobs endpoints, project names validation, airflow tasks and logs endpoints.

fix: use httpx.AsyncClient for requests

---

src/aind_data_transfer_service/server.py
src/aind_data_transfer_service/templates/job_params.html

Closes #302.
- Replaced calls to getCurrentVersion() with a fixed 'v2' value.
- Simplifies modal logic for adding new parameters.
- Ensures new parameters are consistently marked as v2.

feat: removes getCurrentVersion function and hardcodes modal version to v2
