README.md, src/aind_data_transfer_service/templates/index.html
- Adds a statement that tells users to click on the **Help** tab for additional instructions.
- Adds **metadata_dir** to list of columns in README instructions
=> hot-fix: adds a statement for instructions

README.md, src/aind_data_transfer_service/server.py, src/aind_data_transfer_service/templates/index.html, src/aind_data_transfer_service/templates/job_status.html
Adds endpoint for project names
=> hot-fix: adds env var for metadata service url

README.md, src/aind_data_transfer_service/templates/index.html, tests/test_hpc_models.py
Fixes UI to not display processor full name
=> hot-fix: processor full name

pyproject.toml
=> feat: upgrades dependency

.github/workflows/publish_dev.yml, .github/workflows/publish_main.yml, .github/workflows/run_dev_tests.yml, .github/workflows/run_main_tests.yml
Closes #114
- Adds workflows to enable gitflow style releases
=> ci: updates workflows

README.md, src/aind_data_transfer_service/__init__.py
Closes #124
- Fixes url to readthedocs
=> fix: corrects link in README

README.md, src/aind_data_transfer_service/__init__.py
* fix: corrects link in README
=> fix: corrects link in README (#125)

pyproject.toml, src/aind_data_transfer_service/configs/job_configs.py, src/aind_data_transfer_service/configs/job_upload_template.py
Closes #137 
- Upgrades aind-data-transfer-models to v0.7.0, which uses aind-data-schema v1.0
=> feat: upgrades aind-data-schema to v1.0

pyproject.toml, tests/test_server.py
Closes #131 
- Upgrades to latest aind-data-transfer-models, which will allow user to define custom trigger capsule settings a bit better
=> feat: updates to latest aind-data-transfer-models

pyproject.toml
=> build: updates aind-data-transfer-models

pyproject.toml
- Updates to latest version of aind-data-transfer-models to fix validation issue with trigger configs
=> fix: updates to latest transfer models

pyproject.toml
- Uses latest branch to validate job_type field correctly
=> feat: validates job_type field

Dockerfile
=> fix: adds git to docker image

pyproject.toml
Closes #163
- Updates to latest version of aind-data-transfer-models
=> feat: updates transfer models

pyproject.toml
- Updates models to latest version
=> Feat update models

pyproject.toml, src/aind_data_transfer_service/configs/csv_handler.py, src/aind_data_transfer_service/server.py, tests/resources/new_sample.csv, tests/test_csv_handler.py
- Updates version of aind-data-transfer-models
- Adds option for user to set job_type in csv file
=> feat: updates aind-data-transfer-models

docs/examples/example1.csv, docs/source/UserGuide.rst, pyproject.toml, src/aind_data_transfer_service/templates/index.html, src/aind_data_transfer_service/templates/job_status.html
Closes #177 
- Updates core dependencies
- Adds more examples to the readthedocs
=> feat: updates dependencies and docs

pyproject.toml
- Updates aind-data-transfer-models to patch small bug setting institution
=> build: update patch version of transfer models

pyproject.toml, src/aind_data_transfer_service/server.py, tests/test_server.py
Closes #208 
- Validates project names
=> feat: validates project names

.readthedocs.yaml
=> docs: adds sphinx config in readthedocs.yaml

pyproject.toml, tests/test_csv_handler.py
- Upgrades to latest version of the transfer models
=> feat: upgrades transfer models

src/aind_data_transfer_service/models.py, src/aind_data_transfer_service/templates/job_tasks_table.html, tests/test_server.py
- Sends map_index in the airflow logs fetch request to get logs for mapped tasks
=> fix: sends mapped index in logs request

Dockerfile, pyproject.toml, tests/resources/sample_malformed_2.csv
- Updates to python 3.11
- Uses latest aind-data-transfer-models
=> Feat update transfer models

.flake8, pyproject.toml, src/aind_data_transfer_service/models/core.py, tests/test_core.py
- Merges settings into one field
- Adds option to pass in custom command script
=> feat: updates v2 models

src/aind_data_transfer_service/__init__.py, src/aind_data_transfer_service/templates/job_status.html
=> hotfix: sort jobs by submit time desc

.github/workflows/publish_main.yml
=> ci: publish to pypi

pyproject.toml
- Moves legacy dependencies to server optional dependencies
=> build: organizes dependencies

docs/source/UserGuideV2.rst, src/aind_data_transfer_service/models/core.py, tests/resources/legacy_sample.csv, tests/resources/legacy_sample2.csv, tests/resources/new_sample.csv, tests/resources/sample_empty_rows_2.csv, tests/test_core.py, tests/test_csv_handler.py, tests/test_server.py
closes #259 
Removes default value for `job_type` and updates v2 user guide.
=> feat: job_type as required field

src/aind_data_transfer_service/configs/job_upload_template.py, src/aind_data_transfer_service/server.py, tests/test_job_upload_template.py, tests/test_server.py
=> refactor: JobUploadTemplate as pydantic model

docs/examples/remove_source_folders.py, src/aind_data_transfer_service/configs/csv_handler.py, tests/resources/nested_sample.csv, tests/test_csv_handler.py
Closes #272 
Closes #277 
- Allows a user to set a key in the csv file like "behavior.compression_requested.compression_enum"
- Fixes a typo with force_cloud_sync
- Removes deprecated task
=> Feat 277 csv parser

docs/examples/behavior_videos_compression.csv
Add behavior compression example csv. This was copied from /tests/resources/nested_sample.csv, but I updated the modality to `behavior-videos`
=> docs: behavior_videos_compression.csv

docs/source/UserGuideV2.rst, src/aind_data_transfer_service/templates/index.html
Fixes #295 and updates User Guide V2 documentation to move platform under Optional Fields
=> fix: makes job platform optional in UI

docs/examples/custom_codeocean_pipeline_settings.py
- Updates example to include info on how to capture pipeline results to external bucket
=> docs: adds target example
